# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pool:
  vmImage: ubuntu-latest

resources:
  pipelines:
  - pipeline: sourcePipeline
    source: 'iamgauravsatija.Cybria'
    trigger:
      branches:
      - main

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: echo "Triggered by source pipeline"
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project. $(resources.pipeline.sourcePipeline.pipelineName)
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'


