version: '3.8'

services:
  frontend:
    build: ./cybria-FE
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./cybria-BE
    ports:
      - "8005:8005"
    # depends_on:
    #   - db

  db:
    image: mongo
    ports:
      - "27017:27017"
